import { getLanguage } from "./i18n";
const en = {
  play: "PLAY TOGETHER",
  title: "Two magnets. One yard.",
  intro: "Online co-op for two. Shared experience, your own abilities.",
  create: "CREATE ROOM",
  join: "JOIN",
  code: "Room code",
  back: "BACK",
  copy: "COPY CODE",
  copied: "COPIED",
  start: "START TOGETHER",
  waiting: "Waiting for a friend…",
  ready: "Both robots are ready.",
  guest: "Your friend will start the run.",
  connecting: "Connecting…",
  rule: "The yard never pauses. Choose upgrades while moving. Stay beside a fallen teammate for 3 seconds to revive them.",
  closed: "Your teammate left. The room has closed.",
  expired: "This room has expired. Create another room.",
  offline: "Connection lost. Return to the menu to try again.",
  room: "Room unavailable. Check the code or ask for a new one.",
  busy: "The yard is full. Try again shortly.",
  team: "TEAMMATE",
  down: "Down! Your teammate can revive you.",
  revive: "Stand beside your teammate to revive them.",
  upgrade: "CHOOSE AN ABILITY",
  live: "Keep moving · 1 / 2 / 3 to choose",
  leave: "LEAVE ROOM",
  resume: "BACK TO THE YARD",
  menu: "CO-OP MENU",
  running: "The fight continues while this menu is open.",
  again: "PLAY AGAIN",
  hostAgain: "Waiting for the host…",
};
type Copy = typeof en;
const translations: Record<string, Copy> = {
  en,
  tr: {
    play: "BİRLİKTE OYNA",
    title: "İki mıknatıs. Tek hurdalık.",
    intro: "İki kişilik çevrimiçi co-op. Deneyim ortak, yetenekler sana özel.",
    create: "ODA KUR",
    join: "KATIL",
    code: "Oda kodu",
    back: "GERİ",
    copy: "KODU KOPYALA",
    copied: "KOPYALANDI",
    start: "BİRLİKTE BAŞLA",
    waiting: "Arkadaşın bekleniyor…",
    ready: "İki robot da hazır.",
    guest: "Arkadaşın oyunu başlatacak.",
    connecting: "Bağlanılıyor…",
    rule: "Oyun hiç durmaz. Hareket ederken yetenek seç. Düşen arkadaşını kaldırmak için yanında 3 saniye bekle.",
    closed: "Arkadaşın ayrıldı. Oda kapandı.",
    expired: "Odanın süresi doldu. Yeni bir oda kur.",
    offline: "Bağlantı kesildi. Tekrar denemek için menüye dön.",
    room: "Oda bulunamadı veya dolu. Kodu kontrol et.",
    busy: "Hurdalık dolu. Biraz sonra tekrar dene.",
    team: "TAKIM ARKADAŞIN",
    down: "Düştün! Arkadaşın seni kaldırabilir.",
    revive: "Kaldırmak için arkadaşının yanında bekle.",
    upgrade: "YETENEK SEÇ",
    live: "Hareket etmeye devam et · 1 / 2 / 3 ile seç",
    leave: "ODADAN AYRIL",
    resume: "OYUNA DÖN",
    menu: "CO-OP MENÜSÜ",
    running: "Bu menü açıkken savaş devam eder.",
    again: "TEKRAR OYNA",
    hostAgain: "Oda sahibi bekleniyor…",
  },
  de: {
    play: "ZUSAMMEN SPIELEN",
    title: "Zwei Magnete. Ein Hof.",
    intro: "Online-Koop für zwei. Gemeinsame Erfahrung, eigene Fähigkeiten.",
    create: "RAUM ERSTELLEN",
    join: "BEITRETEN",
    code: "Raumcode",
    back: "ZURÜCK",
    copy: "CODE KOPIEREN",
    copied: "KOPIERT",
    start: "GEMEINSAM STARTEN",
    waiting: "Warte auf einen Freund…",
    ready: "Beide Roboter sind bereit.",
    guest: "Dein Freund startet die Runde.",
    connecting: "Verbinden…",
    rule: "Keine Pause. Fähigkeiten beim Bewegen wählen. Bleibe zum Wiederbeleben 3 Sekunden neben deinem Partner.",
    closed: "Dein Partner hat den Raum verlassen.",
    expired: "Raum abgelaufen. Erstelle einen neuen.",
    offline: "Verbindung getrennt. Versuche es im Menü erneut.",
    room: "Raum nicht verfügbar. Prüfe den Code.",
    busy: "Der Hof ist voll. Versuche es später.",
    team: "TEAMKAMERAD",
    down: "Am Boden! Dein Partner kann dich retten.",
    revive: "Bleibe zum Retten neben deinem Partner.",
    upgrade: "FÄHIGKEIT WÄHLEN",
    live: "In Bewegung bleiben · 1 / 2 / 3 wählen",
    leave: "RAUM VERLASSEN",
    resume: "ZURÜCK ZUM SPIEL",
    menu: "KOOP-MENÜ",
    running: "Der Kampf geht bei offenem Menü weiter.",
    again: "NOCH EINMAL",
    hostAgain: "Warte auf den Gastgeber…",
  },
  fr: {
    play: "JOUER ENSEMBLE",
    title: "Deux aimants. Une casse.",
    intro:
      "Coop en ligne à deux. Expérience partagée, capacités individuelles.",
    create: "CRÉER UN SALON",
    join: "REJOINDRE",
    code: "Code du salon",
    back: "RETOUR",
    copy: "COPIER LE CODE",
    copied: "COPIÉ",
    start: "COMMENCER ENSEMBLE",
    waiting: "En attente d’un ami…",
    ready: "Les deux robots sont prêts.",
    guest: "Ton ami lancera la partie.",
    connecting: "Connexion…",
    rule: "Aucune pause. Choisis en te déplaçant. Reste 3 secondes près de ton partenaire à terre pour le relever.",
    closed: "Ton partenaire a quitté le salon.",
    expired: "Salon expiré. Crée un nouveau salon.",
    offline: "Connexion perdue. Réessaie depuis le menu.",
    room: "Salon indisponible. Vérifie le code.",
    busy: "La casse est pleine. Réessaie plus tard.",
    team: "COÉQUIPIER",
    down: "À terre ! Ton partenaire peut te relever.",
    revive: "Reste près de ton partenaire pour le relever.",
    upgrade: "CHOISIR UNE CAPACITÉ",
    live: "Continue de bouger · Choisir avec 1 / 2 / 3",
    leave: "QUITTER LE SALON",
    resume: "REPRENDRE",
    menu: "MENU COOP",
    running: "Le combat continue pendant ce menu.",
    again: "REJOUER",
    hostAgain: "En attente de l’hôte…",
  },
  es: {
    play: "JUGAR JUNTOS",
    title: "Dos imanes. Un desguace.",
    intro:
      "Cooperativo en línea para dos. Experiencia compartida, habilidades propias.",
    create: "CREAR SALA",
    join: "UNIRSE",
    code: "Código de sala",
    back: "VOLVER",
    copy: "COPIAR CÓDIGO",
    copied: "COPIADO",
    start: "EMPEZAR JUNTOS",
    waiting: "Esperando a un amigo…",
    ready: "Los dos robots están listos.",
    guest: "Tu amigo iniciará la partida.",
    connecting: "Conectando…",
    rule: "El juego no se pausa. Elige mientras te mueves. Quédate 3 segundos junto a tu compañero caído para reanimarlo.",
    closed: "Tu compañero ha abandonado la sala.",
    expired: "La sala ha caducado. Crea otra.",
    offline: "Conexión perdida. Reintenta desde el menú.",
    room: "Sala no disponible. Revisa el código.",
    busy: "El desguace está lleno. Inténtalo más tarde.",
    team: "COMPAÑERO",
    down: "¡Has caído! Tu compañero puede reanimarte.",
    revive: "Quédate cerca de tu compañero para reanimarlo.",
    upgrade: "ELIGE UNA HABILIDAD",
    live: "Sigue moviéndote · Elige con 1 / 2 / 3",
    leave: "SALIR DE LA SALA",
    resume: "VOLVER AL JUEGO",
    menu: "MENÚ COOPERATIVO",
    running: "El combate continúa con este menú abierto.",
    again: "JUGAR DE NUEVO",
    hostAgain: "Esperando al anfitrión…",
  },
  pt: {
    play: "JOGAR JUNTOS",
    title: "Dois ímanes. Um ferro-velho.",
    intro:
      "Co-op online para dois. Experiência partilhada, habilidades próprias.",
    create: "CRIAR SALA",
    join: "ENTRAR",
    code: "Código da sala",
    back: "VOLTAR",
    copy: "COPIAR CÓDIGO",
    copied: "COPIADO",
    start: "COMEÇAR JUNTOS",
    waiting: "À espera de um amigo…",
    ready: "Os dois robôs estão prontos.",
    guest: "O teu amigo vai iniciar a partida.",
    connecting: "A ligar…",
    rule: "O jogo não pausa. Escolhe enquanto te moves. Fica 3 segundos junto ao parceiro caído para o reanimar.",
    closed: "O teu parceiro saiu da sala.",
    expired: "A sala expirou. Cria outra.",
    offline: "Ligação perdida. Tenta de novo no menu.",
    room: "Sala indisponível. Verifica o código.",
    busy: "O ferro-velho está cheio. Tenta mais tarde.",
    team: "PARCEIRO",
    down: "Caíste! O teu parceiro pode reanimar-te.",
    revive: "Fica junto ao teu parceiro para o reanimar.",
    upgrade: "ESCOLHE UMA HABILIDADE",
    live: "Continua a mover-te · Escolhe com 1 / 2 / 3",
    leave: "SAIR DA SALA",
    resume: "VOLTAR AO JOGO",
    menu: "MENU CO-OP",
    running: "O combate continua com este menu aberto.",
    again: "JOGAR NOVAMENTE",
    hostAgain: "À espera do anfitrião…",
  },
};
export const ct = (key: keyof Copy) => (translations[getLanguage()] ?? en)[key];
